name: searxng

services:
  searxng:
    container_name: searxng
    image: searxng/searxng:2026.9.30-a9d990033
#   image: docker.io/searxng/searxng:2026.3.29-7ac4ff39f
    restart: unless-stopped

    ports:
      - "10.8.0.1:18080:8080"

    volumes:
      - ./settings.yml:/etc/searxng/settings.yml:ro

    environment:
      SEARXNG_SETTINGS_PATH: /etc/searxng/settings.yml
