services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "18080:8080" # เรียกใช้งานผ่านพอร์ต 18080
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://10.8.0.1:18080/
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID

